[projects."/Users/ymgn/dotfiles"]
trust_level = "untrusted"

[projects."/Users/ymgn"]
trust_level = "untrusted"

[features]
web_search_request = true

[sandbox_workspace_write]
network_access = true

model_reasoning_effort = "high"